// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

type Unit struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UnitCategory struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Units []*Unit `json:"units"`
}
